In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns

In [2]:
data = pd.read_csv("Iris.csv")
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [4]:
data.drop("Id",axis=1,inplace=True)

In [7]:
from sklearn.preprocessing import LabelEncoder
le  = LabelEncoder()
data["Species"] = le.fit_transform(data["Species"])

In [8]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.9           3.0            1.4           0.2        0
2            4.7           3.2            1.3           0.2        0
3            4.6           3.1            1.5           0.2        0
4            5.0           3.6            1.4           0.2        0

In [9]:
data["Species"].value_counts()

0    50
1    50
2    50
Name: Species, dtype: int64

In [10]:
x = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [11]:
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=60)

In [12]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(xtrain,ytrain)

F:\Notes\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [13]:
ypred = lr.predict(xtest)

In [14]:
print(ypred[:10])

[1 1 1 0 1 0 1 0 0 2]


In [15]:
ytest[:10]

69     1
71     1
97     1
42     0
73     1
35     0
67     1
33     0
23     0
133    2
Name: Species, dtype: int32

In [16]:
lr.score(xtest,ytest)

0.9333333333333333

In [17]:
import pickle as pkl
# it is model to save and load model

In [25]:
filename = "iries_model.sav"
pkl.dump(lr,open(filename,"bw"))

In [26]:
loaded_model = pkl.load(open(filename,"br"))
loaded_model

LogisticRegression()

In [27]:
new_data = np.array([7.4,2.8,6.1,1.9]).reshape(1,-1)
new_data

array([[7.4, 2.8, 6.1, 1.9]])

In [28]:
loaded_model.predict(new_data)

F:\Notes\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([2])